name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  IMAGE_NAME: liona/qwertylearner
  DOCKER_USERNAME: liona

jobs:
  get_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git Clone Action
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: Kaiyiwing/qwerty-learner
          path: .
      - run echo "$PWD"

  build-static-files:
    needs: [ get_source ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - run: echo "$PWD"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: |
        echo "$PWD"
        yarn
        yarn build
    - name: store build files
      uses: actions/upload-artifact@v2.3.1
      with:
        name: build-files
        path: src/dist/

  build-docker-image:
    needs: [ build-static-files ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        name: build-files
        path: src/dist/
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
    - name: Log into registry
      run: echo "${{ secrets.PASSWORD }}" | docker login -u $DOCKER_USERNAME --password-stdin
    - name: Push image
      run: |
        # 将所有的大写字母转为小写
        IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')

        # 从 GitHub.ref 中取出版本
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        # 从 tag 名字中替换 v 字符
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        # Use Docker `latest` tag convention
        [ "$VERSION" == "main" ] && VERSION=latest

        echo VERSION=$VERSION
        # 设置镜像 id 和版本号
        docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION
        # 进行 push
        docker push $IMAGE_NAME:$VERSION
